### ISSUE TITLE
Issue: ValueError During Model Training

### ISSUE THREAD

**Issue by jkurpost** [0nurB/BioPredictionRPI-1.0#1]
When running the following command to execute BioPrediction.py:
```
python BioPrediction.py \
    -input_interactions_train datasets/exp_1/RPI369/RPI369_pairs.csv \
    -sequences_dictionary_protein datasets/exp_1/RPI369/RPI369_protein_seq.fa \
    -sequences_dictionary_rna datasets/exp_1/RPI369/RPI369_dna_seq.fa \
    -input_interactions_candidates datasets/exp_1/RPI369/RPI369_candidates_pairs.csv \
    -output datasets/exp_test/
```
The script begins execution and processes the files successfully, but encounters a ValueError during model training due to an empty training dataset.：
```
input_interactions_train - datasets/exp_1/RPI369/RPI369_pairs.csv: Found File
sequences_dictionary_protein - datasets/exp_1/RPI369/RPI369_protein_seq.fa: Found File
sequences_dictionary_rna - datasets/exp_1/RPI369/RPI369_dna_seq.fa: Found File
Topology features extraction fold1
Topology features extraction fold2
Topology features extraction fold3
Topology features extraction fold4
Topology features extraction fold5
Extracting features with MathFeature...
Extracting features with MathFeature...
Checking for imbalanced labels...
There are imbalanced labels...
Checking the best technique...
Applying Random - Undersampling...
     Unnamed: 0_x  Hub Score_x_x  ...  Clustering Centrality_y_y  Core Number Centrality_y_y
0             6.0   6.799821e-19  ...                        0.0                         1.0
1            39.0  -0.000000e+00  ...                        0.0                         1.0
2           171.0  -2.163957e-19  ...                        0.0                         1.0
3           284.0  -2.268879e-18  ...                        0.0                         1.0
4           228.0  -0.000000e+00  ...                        0.0                         1.0
..            ...            ...  ...                        ...                         ...
487          28.0   3.332836e-17  ...                        0.0                         1.0
488          86.0  -1.874301e-18  ...                        0.0                         0.0
489         125.0   3.874098e-19  ...                        0.0                         0.0
490         321.0   4.856663e-18  ...                        0.0                         0.0
491         122.0  -1.784462e-18  ...                        0.0                         1.0

[492 rows x 62 columns]
Creating explanations directory: datasets/exp_test//folds_and_topology_feats/fold1/partial_models/explanations...
Empty DataFrame
Columns: [A_x, C_x, G_x, T_x, AA_x, AC_x, AG_x, AT_x, CA_x, CC_x, CG_x, CT_x, GA_x, GC_x, GG_x, GT_x, TA_x, TC_x, TG_x, TT_x, AAA, AAC, AAG, AAT, ACA, ACC, ACG, ACT, AGA, AGC, AGG, AGT, ATA, ATC, ATG, ATT, CAA, CAC, CAG, CAT, CCA, CCC, CCG, CCT, CGA, CGC, CGG, CGT, CTA, CTC, CTG, CTT, GAA, GAC, GAG, GAT, GCA, GCC, GCG, GCT, GGA, GGC, GGG, GGT, GTA, GTC, GTG, GTT, TAA, TAC, TAG, TAT, TCA, TCC, TCG, TCT, TGA, TGC, TGG, TGT, TTA, TTC, TTG, TTT, A_y, C_y, D, E, F, G_y, H, I, K, L, M, N, P, Q, R, S, ...]
Index: []

[0 rows x 637 columns]
Traceback (most recent call last):
  File "/home/steven/program/BiopredictionRPI/BioPredictionRPI-1.0-main/BioPrediction.py", line 974, in <module>
    fit_mod(input_interactions_train, sequences_dictionary_protein, n_cpu, foutput, candidates, extrac_topo_features = True)
  File "/home/steven/program/BiopredictionRPI/BioPredictionRPI-1.0-main/BioPrediction.py", line 842, in fit_mod
    partial_models2('nameseq', datasets_extr[j], names_math[j], datasets_extr2[j], names_math2[j], train_edges_output[p],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steven/program/BiopredictionRPI/BioPredictionRPI-1.0-main/BioPrediction.py", line 346, in partial_models2
    clf = better_model(X_train, y_train, X_test, y_test, partial_folds+'/model_'+names+'_'+names2+'.sav')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steven/program/BiopredictionRPI/BioPredictionRPI-1.0-main/make_model.py", line 191, in better_model
    clf.fit(X_train, y_train)
  File "/home/steven/anaconda3/envs/bioprediction-rpi/lib/python3.11/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steven/anaconda3/envs/bioprediction-rpi/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steven/anaconda3/envs/bioprediction-rpi/lib/python3.11/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steven/anaconda3/envs/bioprediction-rpi/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "/home/steven/anaconda3/envs/bioprediction-rpi/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1072, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 637)) while a minimum of 1 is required by RandomForestClassifier.
```

**Comment by 0nurB** [comment]
Resolved! It was an issue with the datasets (a test version was sent).
